### PR TITLE
Mention Kotlin version in README

### PR DESCRIPTION
**Pull request by benjaminSchilling33**
Pull request for https://github.com/authpass/biometric_storage/issues/21

### CODE REVIEW

**Comment by hpoul** [comment]
Hi,
Thanks for the pr, but I'm not quite sure all that is required.. it should be enough to tell proguard to use the config from the dependencies, which should be the default? Most of the commit you mention is about adding the config to the package, not the actual app.. so this should but be necessary..
I think I'll have to take a closer look.. proguard config is always a bit magic

**Comment by benjaminSchilling33** [comment]
Thanks, tomorrow I will look into it again.

**Comment by benjaminSchilling33** [comment]
Hi, 
maybe I misunderstood you but I added the same configuration that was applied in the mentioned commit in my app and it works. Of course I'm not 100% sure whether everything I added to the README is necessary, but it seems to be a starting point for further improvements. At least it compiles without any problems afterwards.

**Comment by saschpe** [comment]
I don't think it hurts to mention. The project also fails to compile with Kotlin 1.5.x BTW.

**Comment by hpoul** [comment]
fyi, i've already added the requirement:

      * Make sure to use the latest kotlin version: 
        * `android/build.gradle`: `ext.kotlin_version = '1.4.31'`

I've also just pushed a new version which should fix compatibility with kotlin 1.5.x thanks for reporting @saschpe

**Comment by saschpe** [comment]
> [..]
> I've also just pushed a new version which should fix compatibility with kotlin 1.5.x thanks for reporting @saschpe

I just gave version 2.0.3 a try and I can confirm that the kapt compilation issue is fixed. I can now use Gradle 7.1.1 and Kotlin 1.5.20 in the Android build of my Flutter app. Thanks!

**Pull request closed without merging**
