### PR TITLE
Solving race condition between getting the cipher and decoding the file.

### PR DESCRIPTION
**Pull request by ItzikAlkotzerAidoc**
1. Remove executor and handler from companion object.
2. create new executor for each run of the BiometricPrompt.
3. run the callback from the prompt on the executor thread instead of the main thread.

### CODE REVIEW

**Comment by itaishalom** [comment]
@hpoul That's good, please approve :)

**Comment by itaishalom** [comment]
@hpoul ? It solved my problem, can you please accept this solution.

**Comment by hpoul** [comment]
What is the problem you are trying to solve? Can you create a reproducible problem?

Imho this makes things worse. e.g. creating a new executor for every call and never shutting it down seems a bit weird.

ad 3) This is certainly not correct, see the documentation for MethodChannel: https://docs.flutter.dev/development/platform-integration/platform-channels#channels-and-platform-threading

> The result of the platform side handlers [...] must be invoked on the platform thread

(Except when using the Task Queue API.. which is not used, and I see no reason why it would be beneficial to change that).

**Comment by ItzikAlkotzerAidoc** [comment]
Hey, thanks for the fast response,

I was trying to solve the exception:
AuthException{code: AuthExceptionCode.unknown, message: Unexpected authentication error. null}

It was very hard to reproduce, but it happens when the ui thread is busy, and while we trying to decode the file the chipper is no longer valid.

I moved the Executer out of the Companion objects because fields in the companion object are static, so it’ll keep them for ever, 

Perhaps the better solution is to complete the decoding of the file and only after that run it on the ui thread?

Thanks!
Itzik

**Comment by hpoul** [comment]
> I moved the Executer out of the Companion objects because fields in the companion object are static, so it’ll keep them for ever,

I don't think there is any problem with that.. the plugin instance itself will also always live "forever" (as long as the flutter instance is running). I could only make a difference if you use flutter only in a subset of your application. As long as the flutter engine is running, the plugin would exist anyway.. the only "cleaner" solution would be to keep it in the plugin instance and gracefully shutting it down when the plugin is destroyed..



> Perhaps the better solution is to complete the decoding of the file and only after that run it on the ui thread?

honestly i thought this was the case 🤔 but it seems you are right, currently all file operations seem to be on the ui thread 🤦


I've tried to fix those issues in https://github.com/authpass/biometric_storage/pull/64 .. i've moved the handler and executor into the plugin instance and properly shutdown the executor when the plugin is detached from the flutter engine..
in addition read/write (and encrypt/decrypt) should now be correctly on the executor thread, instead of the main thread.
According to the log output it seems to work so far:

```
D/d.c.b.CryptographyManager: [pool-2-thread-1     ] encrypted 41 (69 output)
D/d.c.b.BiometricStorageFile: [pool-2-thread-1     ] Successfully written 69 bytes.
```

```
D/d.c.b.CryptographyManager: [pool-2-thread-1     ] decrypting 69 bytes (iv: 12, tag: 16)
```

I'm not sure if it would be better to move everything into the executor thread and only switch to the UI thread when necessary (ie. when showing the prompt and returning the result) because those `file.exists()` checks are also synchronous.. but not sure if it is worth switching threads just for checking whether the file exists..
anyway.. at least it should improve things..

**Comment by hpoul** [comment]
Solved in #64 - thanks for bringing this to my attention.

**Pull request closed without merging**
